# Generated by Django 6.0.1 on 2026-01-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('what_you_will_learn', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('thumbnail', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('account_type', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('about', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sec_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.course')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('time_durastation', models.DateTimeField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.section')),
            ],
            options={
                'db_table': 'sub_section',
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.course')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.tag')),
            ],
            options={
                'db_table': 'course_tag',
            },
        ),
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.user')),
            ],
            options={
                'db_table': 'rating_review',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_progress', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.user')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
