# Generated by Django 6.0.1 on 2026-01-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
