# Generated by Django 6.0.1 on 2026-01-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_invoice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='course_progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_progress', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_admin.user')),
            ],
            options={
                'db_table': 'user_course',
            },
        ),
    ]
